# Copyright 2014 The Closure Library Authors. All Rights Reserved.
#
# Use of this source code is governed by the Apache License, Version 2.0.
# See the LICENSE file for details.

sudo: false

install:
  - ./scripts/ci/install_closure_deps.sh

script:
  - ./scripts/ci/compile_closure.sh
  - ./scripts/ci/lint_pull_request.sh
